In [115]:
import pandas as pd
import numpy as np 


In [116]:
dataset=pd.read_csv(r'C:\Users\anonymous\AI\test\likitha\dataset_1.csv')

In [117]:
dataset.isnull().any()

Pregnancies                                        False
 PCOS or Acanthosis nigricans problems in past     False
HOMO IR                                            False
Insulin                                            False
 Diabetes pedigree function                        False
Glucose                                            False
Blood Pressure                                     False
Age                                                False
Outcome                                            False
dtype: bool

In [118]:
dataset

Pregnancies  PCOS or Acanthosis nigricans problems in past   HOMO IR  \
0              6                                            PCOS     1.90   
1              1                                           None      0.50   
2              8                                            PCOS     2.90   
3              1                                           None      0.40   
4              0                                           None      1.98   
5              5                                           None      0.80   
6              3                            Acanthosis Nigricans     1.90   
7             10                                           None      1.10   
8              2            Other Insulin resistance conditions      1.97   
9              8                                            PCOS     1.96   
10             4                                           None      0.90   
11            10                                            PCOS     1.92   
12            10                                           None      0.90   
13             1                                           None      2.00   
14             5                                            PCOS     2.10   
15             7                                            PCOS     2.32   
16             0                                            PCOS     2.80   
17             7                                           None      1.92   
18             1                                           None      0.60   
19             1                            Acanthosis Nigricans     1.90   
20             3                                           None      0.80   
21             8                                           None      0.90   
22             7                                            PCOS     1.97   
23             9                                            PCOS     1.95   
24            11                                            PCOS     1.98   
25            10                                           None      1.92   
26             7            Other Insulin resistance conditions      1.96   
27             1                                           None      0.54   
28            13                                           None      0.34   
29             5                                           None      0.86   
..           ...                                             ...      ...   
469            6                                           None      0.45   
470            1                                           None      0.78   
471            0                                           None      0.40   
472            0                                           None      0.56   
473            7                                           None      0.67   
474            4                                           None      0.76   
475            0                                           None      1.45   
476            2                                           None      1.98   
477            7                                           None      0.50   
478            8                                           None      0.60   
479            4                                           None      0.70   
480            3                                            PCOS     1.90   
481            0                                           None      0.40   
482            4                                           None      0.67   
483            0                                           None      0.56   
484            0                                            PCOS     1.90   
485            0                                           None      1.96   
486            1                                           None      0.56   
487            0                                           None      0.45   
488            4                                           None      0.67   
4

In [119]:
x = dataset.iloc[:,0:-1].values
y = dataset.iloc[:,-1].values

In [120]:
x

array([[6, 'PCOS', 1.9, ..., 148, 72, 50],
       [1, 'None ', 0.5, ..., 85, 66, 31],
       [8, 'PCOS', 2.9, ..., 183, 64, 32],
       ...,
       [5, 'None ', 1.56, ..., 110, 68, 30],
       [2, 'None ', 0.56, ..., 81, 72, 25],
       [7, 'PCOS', 1.98, ..., 195, 70, 55]], dtype=object)

In [121]:
x

array([[6, 'PCOS', 1.9, ..., 148, 72, 50],
       [1, 'None ', 0.5, ..., 85, 66, 31],
       [8, 'PCOS', 2.9, ..., 183, 64, 32],
       ...,
       [5, 'None ', 1.56, ..., 110, 68, 30],
       [2, 'None ', 0.56, ..., 81, 72, 25],
       [7, 'PCOS', 1.98, ..., 195, 70, 55]], dtype=object)

In [122]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [123]:
x[:,1] = lb.fit_transform(x[:,1])

In [124]:
x

array([[6, 3, 1.9, ..., 148, 72, 50],
       [1, 1, 0.5, ..., 85, 66, 31],
       [8, 3, 2.9, ..., 183, 64, 32],
       ...,
       [5, 1, 1.56, ..., 110, 68, 30],
       [2, 1, 0.56, ..., 81, 72, 25],
       [7, 3, 1.98, ..., 195, 70, 55]], dtype=object)

In [125]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder(categorical_features = [2])
x = one.fit_transform(x).toarray()

C:\Users\anonymous\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\anonymous\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [126]:
x

array([[  0.,   1.,   0., ..., 148.,  72.,  50.],
       [  1.,   0.,   0., ...,  85.,  66.,  31.],
       [  0.,   0.,   1., ..., 183.,  64.,  32.],
       ...,
       [  0.,   1.,   0., ..., 110.,  68.,  30.],
       [  1.,   0.,   0., ...,  81.,  72.,  25.],
       [  0.,   1.,   0., ..., 195.,  70.,  55.]])

In [127]:
x=x[:,1:]

In [128]:
x

array([[  1.,   0.,   0., ..., 148.,  72.,  50.],
       [  0.,   0.,   0., ...,  85.,  66.,  31.],
       [  0.,   1.,   0., ..., 183.,  64.,  32.],
       ...,
       [  1.,   0.,   0., ..., 110.,  68.,  30.],
       [  0.,   0.,   0., ...,  81.,  72.,  25.],
       [  1.,   0.,   0., ..., 195.,  70.,  55.]])

In [129]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [130]:
x_test

array([[  0.,   0.,   0., ...,  80.,  55.,  21.],
       [  1.,   0.,   0., ...,  92.,  62.,  44.],
       [  0.,   1.,   0., ..., 161.,  86.,  47.],
       ...,
       [  0.,   0.,   0., ..., 107.,  88.,  31.],
       [  0.,   0.,   0., ...,  84.,   0.,  21.],
       [  0.,   0.,   0., ...,  96.,  64.,  21.]])

In [145]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train =sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [131]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [132]:
model=Sequential()

In [133]:
x_test.shape

(100, 11)

In [134]:
x_train.shape

(399, 11)

In [135]:
model.add(Dense(input_dim=11,init="random_uniform",activation='relu',output_dim=15))#input layer

C:\Users\anonymous\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, activation="relu", units=15, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [136]:
model.add(Dense(output_dim=8,init="random_uniform",activation='relu'))#hidden layer

C:\Users\anonymous\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [137]:
model.add(Dense(output_dim=1,init='random_uniform',activation='sigmoid'))#output layer

C:\Users\anonymous\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [138]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])#adam=batch gradent descent

In [139]:
model.fit(x_train,y_train,epochs=50,batch_size=32)#epochs no of iteration 

Epoch 1/50
399/399 [==============================] - 3s 8ms/step - loss: 0.6907 - acc: 0.6190
Epoch 2/50
399/399 [==============================] - 0s 52us/step - loss: 0.6806 - acc: 0.6441
Epoch 3/50
399/399 [==============================] - 0s 57us/step - loss: 0.6719 - acc: 0.6441
Epoch 4/50
399/399 [==============================] - 0s 67us/step - loss: 0.6664 - acc: 0.6441
Epoch 5/50
399/399 [==============================] - 0s 55us/step - loss: 0.6617 - acc: 0.6441
Epoch 6/50
399/399 [==============================] - 0s 65us/step - loss: 0.6579 - acc: 0.6441
Epoch 7/50
399/399 [==============================] - 0s 82us/step - loss: 0.6548 - acc: 0.6441
Epoch 8/50
399/399 [==============================] - 0s 65us/step - loss: 0.6537 - acc: 0.6441
Epoch 9/50
399/399 [==============================] - 0s 83us/step - loss: 0.6492 - acc: 0.6441
Epoch 10/50
399/399 [==============================] - 0s 55us/step - loss: 0.6455 - acc: 0.6441
Epoch 11/50
399/399 [===================

In [140]:
y_pred = model.predict(x_test)


In [141]:
y_pred=(y_pred>0.5)

In [142]:
y_pred

array([[False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [

In [143]:
y_test

array([0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [146]:
y_p=model.predict(sc.transform(np.array([[0,1,100,1,25,8,115000,24,1,1,100000]])))

C:\Users\anonymous\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [147]:
y_p

array([[1.]], dtype=float32)

In [148]:
y_p=(y_p>0.5)

In [149]:
y_p

array([[ True]])

In [150]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.83